name: "cpp"
version: "1.0.0"
author: "system"
description: "Default C++ project template"

variables:
  PROJECT_NAME: "{{PROJECT_NAME}}"
  AUTHOR_NAME: "{{AUTHOR_NAME}}"
  DATE: "{{DATE}}"

  #PROJECT_DESCRIPTION: "{{PROJECT_DESCRIPTION}}"
  #FEATURE_1: "{{FEATURE_1}}"
  #FEATURE_2: "{{FEATURE_2}}"
  #FEATURE_3: "{{FEATURE_3}}"
  #AUTHOR_GITHUB: "{{AUTHOR_GITHUB}}"
  #AUTHOR_EMAIL: "{{AUTHOR_EMAIL}}"
  #AUTHOR_WEBSITE: "{{AUTHOR_WEBSITE}}"
  #INSTALL_COMMAND: "{{INSTALL_COMMAND}}"
  #USAGE_EXAMPLE: "{{USAGE_EXAMPLE}}"
  #PROJECT_STRUCTURE: "{{PROJECT_STRUCTURE}}"
  #LICENSE: "{{LICENSE}}"
  #VERSION: "{{VERSION}}"
  #DATE_CREATED: "{{DATE_CREATED}}"
  #DATE_UPDATED: "{{DATE_UPDATED}}"

subfolders:
  - include
  - src
  - metadata

files:
  - target: "CMakeLists.txt"
    template: "cmake/CMake_Template.txt"
  - target: "src/main.cpp"
    template: "cpp/main.txt"
  - target: "README.md"
    template: "readme/Readme.txt"
  - target: "LICENSE"
    template: "license"
  - target: "metadata/metadata.json"
    template: "metadata/metadata.txt"


command_mode: cautious
silent_mode: true

commands:
  - command: "cd {{PROJECT_NAME}} && git init"
    description: "Initializing Git repository for {{PROJECT_NAME}}..."
  - command: "cd {{PROJECT_NAME}} && git add ."
    description: "Staging files for first commit..."
  - command: "cd {{PROJECT_NAME}} && git commit -m 'Initial commit'"
    description: "Creating first commit..."